#if !canImport(ObjectiveC)
import XCTest

extension NetworkClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NetworkClientTests = [
        ("testNetworkClient", testNetworkClient),
        ("testStackingHeaders", testStackingHeaders),
        ("testTokenAuth", testTokenAuth),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NetworkClientTests.__allTests__NetworkClientTests),
    ]
}
#endif
